-- Create categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  slug TEXT NOT NULL UNIQUE,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- Create index on slug for faster lookups
CREATE INDEX categories_slug_idx ON categories (slug);

-- Create a junction table for article-category relationships
CREATE TABLE article_categories (
  article_id BIGINT REFERENCES articles(id) ON DELETE CASCADE NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
  PRIMARY KEY (article_id, category_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_categories ENABLE ROW LEVEL SECURITY;

-- RLS policies for categories table
CREATE POLICY "Anyone can read categories" ON categories
  FOR SELECT USING (true);

CREATE POLICY "Admin can manage categories" ON categories
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- RLS policies for article_categories table
CREATE POLICY "Anyone can read article_categories" ON article_categories
  FOR SELECT USING (true);

CREATE POLICY "Admin can manage article_categories" ON article_categories
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Add some initial categories
INSERT INTO categories (name, slug, description) VALUES
('Technology', 'technology', 'Articles about tech trends, gadgets, and innovations'),
('Business', 'business', 'Business news, market trends, and economic updates'),
('Entertainment', 'entertainment', 'Latest in movies, music, celebrities, and pop culture'),
('Health', 'health', 'Health news, medical breakthroughs, and wellness tips'),
('Science', 'science', 'Scientific discoveries, space exploration, and research'),
('Politics', 'politics', 'Political news, policy changes, and government affairs');